using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Chiusino
{
    public static class WordGenerator
    {
        private static readonly List<string> Parole = new List<string>
        {
             "albero", "casa", "padella", "auto", "sedia", "tavolo", "bicicletta", "telefono", "computer", "lampada",
    "libro", "penna", "forno", "frigo", "divano", "tazza", "piatto", "sedia", "letto", "scopa",
    "giocattolo", "telefono", "carrozza", "porta", "finestra", "specchio", "mattone", "tetto", "muro", "pavimento",
    "griglia", "tenda", "cuscino", "armadio", "spazzola", "bottiglia", "zaino", "borsa", "giubbotto", "scarpa",
    "collana", "anello", "orologio", "banca", "scaffale", "cartella", "piantina", "frutta", "verdura", "pesce",
    "pizza", "panino", "coltello", "forchetta", "cucchiaio", "bottiglia", "bicchiere", "tavolo", "cuscino", "fazzoletto",
    "asciugamano", "sapone", "doccia", "vasca", "spazzolino", "shampoo", "crema", "spugna", "rasoio", "spazzola",
    "cosmetico", "denti", "dentifricio", "setaccio", "secchio", "pala", "piccone", "martello", "cacciavite", "pinza",
    "riga", "metro", "compasso", "molecola", "microscopio", "proiettore", "scanner", "fotocamera", "televisore", "radio",
    "altoparlante", "cuffia", "microfono", "mixer", "frullatore", "tostapane", "frigorifero", "forno", "stufa", "condizionatore",
    "ventilatore", "ascensore", "scala", "cavatappi", "sciarpa", "guanto", "ombrello", "stivale", "piumino", "giacca",
    "pantalone", "maglietta", "camicia", "giubbotto", "berretto", "occhiali", "scarpa", "stivale", "sneaker", "pantofola",
    "gonna", "pantaloncino", "felpa", "sweatshirt", "corpetto", "canottiera", "tutina", "pigiama", "telo", "panno",
    "piumone", "materasso", "coperta", "tappeto", "carta", "penna", "matita", "gessetto", "pastello", "carta da regalo",
    "foglietto", "agenda", "diario", "libro", "quaderno", "cartella", "penna", "evidenziatore", "astuccio", "gomme",
    "raccoglitore", "cartoncino", "scotch", "colla", "forbici", "taglierino", "spago", "nastro", "fogli", "cartone",
    "carta igienica", "scottex", "tovagliolo", "panno", "stoviglia", "ciotola", "bicchiere", "cucchiaio", "forchetta", "coltello",
    "piatto", "piatto fondo", "piattino", "bicchiere", "caffettiera", "tazzina", "tazzone", "brocca", "caraffa", "stampo",
    "padella", "pentola", "casseruola", "friggitore", "griglia", "teglia", "mattarello", "sacchetto", "confezione", "busta",
    "contenitore", "barattolo", "cesto", "canestro", "secchio", "pala", "secchiello", "tubetto", "conserva", "scatola",
    "cassettiera", "armadio", "scaffale", "cassetto", "scatolone", "scaffale", "mobile", "poltrona", "divano", "sedia",
    "tavolo", "scrivania", "panca", "pouf", "lettino", "letto", "comodino", "lampada", "porta", "finestra", "specchio",
    "tappeto", "quadri", "pittura", "scultura", "vase", "pianta", "fiore", "ceramica", "pietra", "marmo", "legno",
    "metallo", "vetro", "plastica", "carta", "cartone", "acciaio", "rame", "oro", "argento", "platino", "diamante",
    "legna", "carbone", "combustibile", "olio", "benzina", "gas", "petrolio", "gasolio", "metano", "fossile", "acqua",
    "liquido", "gelo", "polvere", "sabbia", "terra", "roccia", "clay", "polistirolo", "gomma", "silicone", "argilla",
    "sapone", "detersivo", "shampoo", "bagnoschiuma", "detergente", "detersivo", "candeggina", "disinfettante", "acido", "sale",
    "pepe", "spezie", "sale", "zucchero", "farina", "miele", "olio", "burro", "formaggio", "latte", "yogurt",
    "uovo", "carne", "pollo", "manzo", "agnello", "maiale", "bacon", "prosciutto", "salsiccia", "tonno", "pesce",
    "salame", "insalata", "spinaci", "pomodoro", "carota", "cavolfiore", "broccoli", "melanzana", "patata", "peperone",
    "cipolla", "aglio", "prezzemolo", "basilico", "origano", "rosemary", "salvia", "timo", "menta", "erba cipollina",
    "tartufo", "fungo", "asparagi", "cipollotto", "peperoncino", "legume", "pisello", "fagiolo", "ceci", "soia",
    "farro", "riso", "pasta", "couscous", "cereali", "riso", "grano", "frumento", "mais", "avena", "barley", "orzo",
    "carboidrato", "proteina", "vitamina", "fibra", "mineral", "zinc", "ferro", "calcio", "potassio", "magnesio", "selenio",
    "iodio", "cromo", "rame", "fluoro", "vitamina C", "vitamina A", "vitamina D", "vitamina E", "acido folico", "biotina",
    "cobalamina", "amminoacido", "glucidi", "lipidi", "grassi", "acidi grassi", "colesterolo", "omega 3", "omega 6", "omega 9",
    "carotenoidi", "flavonoidi", "polifenoli", "antiossidante", "collagene", "elastina", "fibra", "glutine", "lattosio",

    "tenda", "pallone", "racchetta", "panca", "scarpette", "guantoni", "elastico", "pallone da calcio", "pallone da basket", "pallone da rugby",
    "pattini", "bicicletta", "monopattino", "scooter", "skateboard", "pattini a rotelle", "canoa", "kayak", "vela", "surf",
    "tavola da snowboard", "tavola da surf", "occhiali da sole", "ombrello", "cappello", "pantaloncini", "camicia", "t-shirt", "giubbotto", "pigiama",
    "suit", "maschera", "cintura", "cravatta", "boccale", "bicchiere da birra", "tazza da caffè", "bicchiere da vino", "coppa", "piattino",
    "mestolo", "cucchiaio di legno", "coltello da cucina", "forchetta", "pizzaiola", "grattugia", "frusta", "mixer", "frullatore", "macchina per caffè",
    "tostapane", "forno a microonde", "piastra", "pentola a pressione", "spremiagrumi", "sbattitore", "bilancia", "microonde", "frigorifero", "congelatore",
    "lavatrice", "lavastoviglie", "asciugatrice", "ferro da stiro", "stendibiancheria", "tavolo da stiro", "cesto della biancheria", "scopa elettrica", "aspirapolvere",
    "deumidificatore", "umidificatore", "ventilatore", "condizionatore", "stufa", "termosifone", "calorifero", "radiatore", "scaldabagno", "stendino",
    "zaino", "borsa", "pochette", "marsupio", "valigia", "cassetto", "scaffale", "cabina armadio", "scrivania", "computer", "monitor", "tastiera", "mouse",
    "tablet", "smartphone", "caricabatterie", "power bank", "cavo USB", "cuffie", "altoparlante", "televisore", "stereo", "videocamera", "fotocamera", "smartwatch",
    "action cam", "videoregistratore", "modem", "router", "telecomando", "ripetitore", "consolle", "gioco da tavolo", "mazzo di carte", "puzzle", "dado",
    "paletta", "forbici", "spazzola", "pettine", "limetta", "pinzetta", "riga", "carta adesiva", "forbici da cucito", "ago", "filo", "toppa", "cucchiaio",
    "bicchiere di plastica", "piatto di plastica", "piattino", "tovaglietta", "pannolino", "carrozzina", "culla", "sedia a dondolo", "porte", "cancello", "muro",
    "tetto", "capannone", "magazzino", "stanza", "ingresso", "corridoio", "garage", "cantina", "sottoscala", "soffitta", "balcone", "veranda", "finestra",
    "porta finestra", "portafinestra", "vetrata", "termometro", "barometro", "igrometro", "orologio", "calendario", "agenda", "libro", "quaderno", "penna",
    "matita", "gesso", "tavoletta", "calcolatrice", "mappa", "atlas", "bussola", "bussole", "termometro da cucina", "orologio da parete", "tavolino", "trono",
    "fagotto", "strumento musicale", "violino", "chitarra", "batteria", "pianoforte", "flauto", "clarinetto", "saxofono", "tromba", "trombone", "contrabbasso",
    "batteria elettronica", "organo", "pianoforte digitale", "cassa acustica", "amplificatore", "microfono", "altoparlante", "cuffie", "cavo audio", "strumento per accordatura",
    "pennello", "cavalletto", "pittura ad olio", "pittura ad acquerello", "ceramica", "argilla", "pasta modellabile", "cartoncino", "colla a caldo", "colla stick",
    "scotch", "nastro adesivo", "fogli", "matita colorata", "pastelli", "acrilico", "acquerelli", "sacchetto", "busta", "sacco", "confezione", "scatola", "barattolo",
    "vasetto", "scaffale", "cassettiera", "comò", "libreria", "lampada da tavolo", "lampada da parete", "torcia", "candelabro", "candela", "acqua minerale", "beverone",
    "detergente", "detergente per piatti", "detergente per superfici", "detersivo", "acido muriatico", "ammorbidente", "polvere per lavatrice", "candeggina", "flacone", "spray",
    "carta igienica", "salviette", "spugna", "paletta", "secchio", "frusta", "grattugia", "teglia", "stampo", "casseruola", "forno", "griglia", "spremiagrumi", "coltello",
    "forchetta", "cucchiaio", "coltello da cucina", "macchina per pasta", "grattugia", "frullatore", "sminuzzatore", "set di coltelli", "padella", "piano cottura", "forno",
    "caffettiera", "tazza", "piatto", "bicchiere", "bicchiere di vetro", "caraffa", "brocca", "portaoggetti", "portafoto", "portacandele", "portafiori", "portachiavi",
    "cassetta degli attrezzi", "cacciavite", "pinza", "martello", "chiave inglese", "chiave a brugola", "chiave a tubo", "nastro adesivo", "cintura", "camicia", "giacca",
    "pantaloni", "maglietta", "felpa", "maglione", "berretto", "guanti", "scaldacollo", "pigiama", "tuta", "camicia da notte", "sciarpa", "gonna", "pantaloncini",
    "tacchi", "sandali", "scarpe da ginnastica", "stivale", "pantofole", "ciabatte", "scarpe", "scarponi", "guanto da calcio", "scarpe da trekking", "sandali", "stivali",
    "spazzola per capelli", "pettine", "asciugacapelli", "stiratore", "cosmetico", "dentifricio", "spazzolino", "shampoo", "bagnoschiuma", "olio essenziale", "crema",
    "profumo", "olio per capelli", "deodorante", "sapone", "spugna", "scrub", "asciugamano", "set per manicure", "tagliaunghie", "set per pedicure", "crema per mani",
    "crema per piedi", "scaldacera", "ceretta", "filo interdentale", "spazzolino per denti", "dentifricio sbiancante", "spazzola per il corpo", "spazzola per capelli",
    "protesi", "parrucca", "cuscino", "guanciale", "coperta", "piumone", "morbidezza", "materasso", "copriletto", "lenzuola", "telo da bagno", "accappatoio", "asciugamani",
     "rastrello", "zappa", "vanga", "pala", "cesoia", "secchio da giardinaggio", "canna da pesca", "pesciera", "stivali da giardino", "guanti da giardinaggio",
    "spruzzatore", "tutore per piante", "annaffiatoio", "fertilizzante", "compost", "terrario", "semina", "seme", "pianta da vaso", "terreno", "potatura",
    "scaletta", "panchina da giardino", "amaca", "gazebo", "ombrellone", "tavolo da giardino", "sedia da giardino", "fioriera", "cerchio per piante", "concime",
    "aspiratore", "seghetto", "cancello da giardino", "porte scorrevoli", "recinzione", "tagliasiepi", "toilette", "sedia sdraio", "carrello da giardino", "tagliarami",
    "potatore", "torcia da giardino", "griglia per barbecue", "set per barbecue", "graticola", "asciugacapelli", "asciugacapelli professionale", "piastre per capelli",
    "phon", "molletta per capelli", "fascetta per capelli", "spazzola per capelli", "pettine", "shampoo per capelli", "maschera per capelli", "olio per capelli", "gell",
    "crema per il corpo", "crema per il viso", "crema idratante", "detergente viso", "tonico", "trattamento per pelle", "scrub corpo", "acqua micellare", "gel doccia",
    "olio da massaggio", "detersivo intimo", "trattamento anticaduta", "burro di karité", "olio di cocco", "crema solare", "lozione doposole", "profumo", "bagnoschiuma",
    "sapone liquido", "deodorante", "balsamo labbra", "acqua termale", "set manicure", "cera depilatoria", "strisce depilatorie", "spazzola per il corpo", "ferro da stiro",
    "beauty case", "portaspazzolino", "set trucco", "fondotinta", "mascara", "rossetto", "fard", "ombretto", "correttore", "pennelli per trucco", "matita occhi",
    "sopracciglia", "piegaciglia", "struccante", "serum", "trattamento anti rughe", "set per pedicure", "tagliaunghie", "limetta", "pinzetta", "forbici per sopracciglia",
    "pediluvio", "asciugamani", "accappatoio", "telo mare", "asciugamano da bagno", "cuscino per massaggio", "tappetino yoga", "palla fitness", "panca da allenamento",
    "bilancia", "cronometro", "orologio sportivo", "fitness tracker", "tappeto da ginnastica", "pesi", "manubri", "stepper", "corda per saltare", "anello per yoga",
    "palla medica", "hula hoop", "banca da palestra", "kettlebell", "tapis roulant", "panca addominali", "cyclette", "ellittica", "spinning bike", "sedia per ufficio",
    "scrivania da ufficio", "computer portatile", "desktop", "mouse", "tastiera", "monitor", "stampante", "scanner", "ripetitore", "router", "modem", "televisore",
    "smartphone", "tablet", "telecomando", "sintonizzatore", "soundbar", "lettore CD", "DVD", "Blu-ray", "videogiochi", "consolle", "videocamera", "telecamera", "fotocamera",
    "flash", "obiettivo", "treppiede", "custodia per fotocamera", "copriobiettivo", "macro", "lente", "teleobiettivo", "batteria", "caricabatterie", "disco rigido",
    "scheda SD", "USB", "power bank", "auricolari", "cuffie bluetooth", "altoparlante portatile", "microfono", "amplificatore", "audiofilo", "supporto per smartphone",
    "caricabatterie wireless", "televisore smart", "consolle di gioco", "controller", "gioco da tavolo", "mazzo di carte", "dado", "puzzle", "tappeto", "piastrelle",
    "specchio", "lampada da tavolo", "cuscino decorativo", "tappetino da yoga", "fiore artificiale", "vase", "corona di fiori", "portaombrelli", "portaoggetti",
    "portachiavi", "portafoto", "portacandele", "lanterna", "candelabro", "candelina", "faro", "orologio da parete", "quadrato", "quadrilatero", "cerchio", "rettangolo",
    "pendolo", "calendario", "agendina", "diario", "taccuino", "quaderno", "penna", "matita", "gesso", "gomma", "righello", "carta da lettera", "cartoncino",
    "busta", "francobollo", "marcatore", "pennarello", "nastro adesivo", "spago", "colla", "forbici", "taglierino", "attrezzi da falegname", "trapano", "martello",
    "cacciavite", "pinza", "chiave inglese", "saldatore", "levigatrice", "seghetto", "scalpello", "pialla", "forbici da giardinaggio", "motosega", "motocoltivatore",
    "vanga", "cesoia", "zappa", "rastrello", "potatore", "spazzatrice", "tagliasiepi", "irrigatore", "semina", "terreno", "prato", "erbicida", "concime", "giardiniere",
    "pianta da interno", "bonsai", "cactus", "albero", "arbusto", "rosa", "orchidea", "giglio", "piante grasse", "aiuola", "giardino", "arredamento da giardino",
    "cassetto per attrezzi", "cassetta di attrezzi", "armadio da giardino", "carrello", "ciotola", "scaletta", "griglia da barbecue", "barbecue a gas", "fuoco",
    "fumo", "fiaccola", "braciere", "carbonella", "accendino", "fiammifero", "torcia", "candela", "bicchiere da vino", "tazza da caffè", "tazza da tè", "coppa",
    "bicchiere di plastica", "piatto fondo", "piattino", "forchetta", "coltello", "cucchiaio", "bicchiere di carta", "bicchiere da birra", "piatto da pizza", "piatto piano",
    "padella", "pentola", "teglia", "casseruola", "stampo", "bustina di tè", "busta di zucchero", "sacchetto di sale", "bustina di pepe", "barattolo di miele", "pasta",
    "riso", "farina", "cereali", "legumi", "fagioli", "piselli", "ravioli", "lasagna", "spaghetti", "penne", "maccheroni", "farfalle", "fusilli", "tortiglioni",
    "pasta fresca", "cous cous", "cuscus", "caponata", "polenta", "patate", "carote", "finocchio", "peperoni", "melanzane", "asparagi", "piselli", "zucchine",
    "funghi", "pomodori", "cipolle", "peperoncino", "aglio", "origano", "basilico", "rosmarino", "prezzemolo", "salvia", "menta", "timo", "curcuma", "zenzero",
    "miele", "olio d'oliva", "burro", "panna", "latte", "uova", "formaggio", "yogurt", "salame", "prosciutto",    "ventaglio", "archibugio", "mandolino", "lanterna magica", "astrolabio", "meridiana", "arazzo", "tornio",
    "targa", "copricapo", "monocolo", "botticella", "trottola", "tamburello", "carillon", "aquilone", "pomolo",
    "catapulta", "obelisco", "dado a venti facce", "calamaio", "pressa", "macina", "pendolo", "globo terrestre",
    "planisfero", "cassa armonica", "binocolo", "siluro", "galeone", "lancia", "spada laser", "rullino fotografico",
    "micrometro", "contagiri", "tastierino", "carro funebre", "grattacielo", "torre d'assedio", "pennacchio",
    "fiocina", "parabola satellitare", "aliante", "ventilatore manuale", "freccia", "drone", "lavagna luminosa",
    "fiammifero", "trappola per topi", "medaglia", "elmetto", "vialetto", "ferrovia", "spugna di mare", "anfora",
    "clessidra", "scrigno", "damigiana", "scudo", "scarabeo", "vanga telescopica", "carretto dei gelati",
    "bastone per selfie", "secchiello per il ghiaccio", "proiettore di stelle", "cassetta per lettere", "trombone",
    "cembalo", "giavellotto", "scialuppa", "vascello", "giostra", "pergamena", "tastierino numerico", "sottomarino",
    "strabismo", "guinzaglio per animali", "spadone", "canna da zucchero", "fionda", "bastone da passeggio",
    "arco e frecce", "fioretto", "ventosa", "levigatrice", "argano", "carrucola", "autobus a due piani",
    "poltrona reclinabile", "macchina del caffè automatica", "robot da cucina", "campanile", "vela latina",
    "osservatorio", "nave a vapore", "macchina a vapore", "fotocopiatrice", "tastiera ergonomica", "pedaliera",
    "cinturone", "termocamera", "fornello a induzione", "kit da sommelier", "mola", "stilo", "sassofono basso",
    "plettri per chitarra", "zampogna", "arpa", "arpa celtica", "cornamusa", "zattera", "collare per gatti",
    "trasformatore", "indicatore di direzione", "goniometro", "livella laser", "telescopio riflettore",
    "cronografo", "tamburo a cornice", "arpa eolica", "giostra di cavalli", "moto d'acqua", "hoverboard",
    "ventilatore a pedale", "comando a distanza", "mappamondo interattivo", "trampolino elastico", "bilanciere",
    "calibro digitale", "morsa", "scatola nera", "radar", "radio portatile", "zattera gonfiabile", "ponte levatoio",
    "campanello da tavolo", "sacco da boxe", "sedia a rotelle elettrica", "paracadute", "sasso dipinto",
    "macchina per popcorn", "stampante 3D", "distanziatore", "specchio concavo", "orologio a cucù", "rosario",
    "cannocchiale", "scultura astratta", "ombrello giapponese", "tappo per vino", "scarabeo di giada", "motosega",
    "seghetto alternativo", "blocco note elettronico", "lampada di lava", "generatore eolico", "statuetta in bronzo",
    "collare antipulci", "mattoncino LEGO", "teleobiettivo macro", "fotogramma", "scrivania sospesa",
    "tavolo rotondo", "campanello senza fili", "scanner per impronte", "trapano manuale", "barometro analogico",
    "circuito stampato", "proiettore portatile", "asciuga mani elettrico", "pompa per bicicletta", "statuetta di ceramica",
    "tagliaerba automatico", "mini frigorifero", "microfono cardioide", "antifurto", "scarpiera", "tastiera MIDI",
    "macchina fotografica istantanea", "stazione meteorologica", "kit di primo soccorso", "misuratore di pressione",
    "decoder", "ponte sospeso", "bracciale in cuoio", "orologio solare", "astuccio rigido", "lente d'ingrandimento LED",
    "pannello fotovoltaico", "friggitrice ad aria", "macinacaffè", "serbatoio", "bivacco portatile", "torcia UV",
    "incubatrice", "serra idroponica", "stufa a pellet", "carrello pieghevole", "tettoia solare", "attrezzo multifunzione",
    "griglia portatile", "scatola delle meraviglie", "chitarra classica", "arpa bardica", "grimaldello",
    "fune di sicurezza", "ombrello riflettente", "tessera magnetica", "libreria girevole", "porta scorrevole",
    "campana tibetana", "vetrina refrigerata", "ombrellone da spiaggia", "granchio meccanico", "bandana",
    "stampo per biscotti", "decorazioni natalizie", "kit per immersioni", "occhiali a specchio", "poltrona sospesa",
    "filtro per acqua", "macchina fotografica subacquea", "kit di sopravvivenza", "mantella impermeabile",
    "zattera rigida", "bilancia a gancio", "macchina del fumo", "calorifero portatile", "serbatoio portatile",
    "set di candele profumate", "scopa robotizzata", "motore fuoribordo", "bussola digitale", "paralume decorativo",
    "set per cocktail", "proiettore cinematografico", "strada a pedaggio", "faro di segnalazione", "ventilatore a torre",
    "bilancino di precisione", "accendino tempesta", "marsupio impermeabile", "zaino tecnico", "supporto ergonomico",
    "pedaliera per videogiochi", "stazione di ricarica", "monitor curvo", "sedia ergonomica", "kit da viaggio",
    "radio AM/FM", "ponte mobile", "giocattolo interattivo", "canna per aquiloni", "proiettore laser", "rasoio elettrico",
    "scheda audio esterna", "penna stilografica", "stetoscopio", "stampo per cubetti di ghiaccio", "plancia di comando",
    "macchina per pasta fresca", "elica per barca", "canna telescopica", "macchina per il gelato", "matrioska",
    "finestra a cupola", "specchio da trucco", "orologio da taschino", "cuscino riscaldato", "scarponi da neve",
    "tubo telescopico", "giostra da giardino", "amaca portatile", "torcia dinamica", "mola da banco", "sci di fondo",
    "set di stecche da biliardo", "bocce", "pattini da ghiaccio", "elastico fitness", "telemetro", "spalliera svedese",
    "porta palloni", "binocolo notturno", "ferro per arricciare capelli", "set per fonduta", "kit per vinificazione",
    "contagocce", "ferro da golf", "lama da sci", "kit di potatura", "kit per bonsai", "serratura a combinazione",
    "kit per orologiaio", "battipista", "coltello da collezione", "statuetta etnica", "set di pennelli artistici",
    "soffiatore per foglie", "robot aspirapolvere", "lanciatore di coriandoli", "spatola magnetica",            "Cane", "Gatto", "Leone", "Elefante", "Tigre", "Cavallo", "Mucca", "Pecora", "Scimmia", "Pinguino",
            "Canguro", "Orso", "Zebra", "Panda", "Ippopotamo", "Cervo", "Giraffa", "Koala", "Rinoceronte", "Lupo",
            "Volpe", "Coniglio", "Furetto", "Squalo", "Balena", "Delfino", "Polpo", "Tartaruga", "Coccodrillo", "Serpente",
            "Aquila", "Falco", "Gufo", "Piccione", "Pappagallo", "Colibrì", "Struzzo", "Gabbiano", "Cigno", "Passero",
            "Picchio", "Corvo", "Germano reale", "Calabrone", "Marmotta", "Riccio", "Cavalluccio marino", "Medusa", "Stella marina",
            "Gambero", "Granchio", "Lucertola", "Gecko", "Iguana", "Camaleonte", "Scorpione", "Ragno", "Farfalla", "Marmocchi",
            "Ratto", "Topolino", "Foca", "Leopardo", "Cheetah", "Pantera", "Ghepardo", "Lince", "Gatto selvatico", "Coyote",
            "Bisonte", "Alce", "Antilope", "Bavetta", "Oca", "Anatra", "Gallo", "Gallina", "Tordo", "Starna", "Pavone",
            "Tetraone", "Civetta", "Pipistrello", "Cervo volante", "Picchio verde", "Topo", "Senza peli", "Fennec", "Panda rosso",
            "Cavallo marino", "Lupo grigio", "Antilope addax", "Armadillo", "Cervo sika", "Mandrillo", "Babbuino", "Scimmia ragno",
            "Macaco", "Tamarino", "Ape", "Mosca", "Coleottero", "Scarabeo", "Falena", "Lucciola", "Zanzara", "Formica", "Termite",
            "Lombrico", "Scivola", "Salamandra", "Tricheco", "Leopardo delle nevi", "Tigre bianca", "Mole", "Talpa", "Becco d'anatra",
            "Rana", "Girino", "Camaleonte", "Tucano", "Ibis", "Gru", "Cervo delle montagne", "Moleca", "Marmotta delle rocce",
            "Morsa", "Foca monaca", "Mouflon", "Istrice", "Urso bruno", "Cinghiale", "Ocelot", "Scimmia capucino", "Leone marino",
            "Tuttiol", "Lynx", "Coyote rosso", "Muflone", "Pipistrello pallido", "Aguglia", "Piranha", "Salmone", "Trota",
            "Pesce gatto", "Nettare", "Squalo martello", "Nutria", "Tassia", "Rocca", "Triglia", "Ostrica", "Astice",
            "Tartaruga terrestre", "Corallo", "Riccio di mare", "Cernia", "Orata", "Riccio delle rocce", "Libellula",
            "Squalo bianco", "Mantis religiosa", "Ammorbidente", "Rana bullfrog", "Giaguaro", "Fossa", "Civetta delle nevi",
            "Grillo", "Varano", "Volpe artica", "Civetta scura", "Gatto leopardo", "Coniglio selvatico", "Martora",
            "Cacatua", "Cacatua rosa", "Cavalletta", "Lucertola rossa", "Pipistrello marrone", "Dromedario", "Cervo rosso",
            "Pipistrello del frutto", "Cervo europeo", "Simpatico", "Fagiano", "Mucca americana", "Giaguaro","abissale",
            "adamantino",
            "affabile",
            "anacronistico",
            "austero",
            "bucolico",
            "candido",
            "ceruleo",
            "corposo",
            "crepuscolare",
            "desueto",
            "effimero",
            "elefantiaco",
            "ermetico",
            "evanescente",
            "fastoso",
            "fluviale",
            "fulgido",
            "granuloso",
            "idilliaco",
            "imponente",
            "ineffabile",
            "infausto",
            "iridescente",
            "lapidario",
            "languido",
            "limpido",
            "luttuoso",
            "magnetico",
            "manierato",
            "mestoso",
            "onirico",
            "orwelliano",
            "pomposo",
            "prezioso",
            "recondito",
            "sontuoso",
            "sotterraneo",
            "spigoloso",
            "sussurrante",
            "tetro",
            "timoroso",
            "vagheggiante",
            "vellutato",
            "vitreo",

            // Oggetti di vecchia data o particolari
            "abat-jour",
            "alabarda",
            "anfora",
            "astrolabio",
            "baldacchino",
            "balestra",
            "bastone da passeggio",
            "brocca",
            "calamaio",
            "candeliere",
            "carrozza",
            "clessidra",
            "cocchio",
            "coppa d'argento",
            "corno da caccia",
            "corteccia d'alloro",
            "crinolina",
            "dagherrotipo",
            "diadema",
            "elmo",
            "ferro di cavallo",
            "fiaschetta",
            "forziere",
            "galeone",
            "lanterna",
            "monocolo",
            "orologio a cipolla",
            "palafitta",
            "papiro",
            "pergamena",
            "pesasoldi",
            "piumino da cipria",
            "pochette",
            "poltrona bergère",
            "portagioie",
            "portapiume",
            "putto",
            "selciato",
            "specchietto tascabile",
            "spinetta",
            "stilografo",
            "tamburello",
            "telescopio",
            "terrecotte",
            "tirapugni",
            "ventaglio",
            "zampogna", "abbandonare", "abbattere", "abbellire", "abbinare", "abbracciare", "abbuiare", "abdicare", "abolire", "accedere", "accendere",
            "acchiappare", "accogliere", "accomandare", "accompagnare", "accorgere", "accumulare", "accusare", "adelantare", "adorare", "affermare",
            "affezionare", "affidare", "affrettare", "affrontare", "aggiornare", "aggredire", "agire", "allacciare", "allarmare", "allenare",
            "alleviare", "allineare", "allontanare", "alludere", "alzare", "amare", "andare", "apparecchiare", "apparire", "appetire", "apprendere",
            "aprire", "arrampicare", "arrivare", "ascoltare", "aspettare", "assaporare", "assicurare", "assistere", "associare", "assumere",
            "attaccare", "attrarre", "avanzare", "avere", "avvertire", "baciare", "ballare", "barare", "bastare", "battezzare", "battere", "bavare",
            "bere", "bisognare", "bollire", "bordare", "brillare", "bruciare", "cadere", "calcolare", "cambiare", "cancellare", "capire", "caricare",
            "catturare", "cercare", "chiedere", "chiamare", "chiudere", "cogliere", "cominciare", "comprare", "concedere", "concludere", "conoscere",
            "consigliare", "consolidare", "costruire", "cucinare", "dare", "decidere", "definire", "deludere", "desiderare", "destinare", "determinare",
            "dimenticare", "dipendere", "dire", "dipingere", "direzionare", "distinguere", "distruggere", "diventare", "dividere", "dormire", "durare",
            "elencare", "evidenziare", "esaminare", "eseguire", "essere", "esporre", "esprimere", "esplodere", "essere", "evaporare", "fallire", "fermare",
            "ferire", "figliare", "fidare", "fingere", "fissare", "flettere", "fluttuare", "fornire", "frequentare", "fronteggiare", "galleggiare",
            "guardare", "gustare", "incontrare", "informare", "insegnare", "intendere", "inviare", "isolare", "lavorare", "leggere", "lanciare", "mangiare",
            "mandare", "marcare", "mentire", "meravigliare", "mettere", "mordere", "muovere", "nascere", "navigare", "necessitare", "negare", "noleggiare",
            "notare", "nuotare", "offrire", "opporsi", "organizzare", "osservare", "ottenere", "percepire", "perdere", "permettere", "piacere", "picchiare",
            "piegare", "piombare", "porre", "posare", "pregare", "preservare", "prestare", "provare", "promettere", "protegger", "pungere", "raggiungere",
            "ragionare", "reagire", "realizzare", "restare", "ripetere", "riposare", "rispondere", "risvegliare", "rubare", "salire", "saldare", "saltare",
            "sapere", "scolpire", "scrivere", "scuotere", "sedere", "segnare", "separare", "sognare", "sospendere", "spiegare", "spingere", "staccare",
            "stare", "studiare", "sublimare", "superare", "supportare", "sussurrare", "svegliare", "svenire", "svoltare", "tendere", "terminare", "tessere",
            "tirare", "toccare", "tornare", "tradurre", "trattare", "trattenere", "trascinare", "trasferire", "trasformare", "trattare", "uscire", "valere",
            "vedere", "venire", "vincere", "visitare", "votare", "volare", "volere", "vomitare", "zoppicare", "zuccherare", "zuffare", "adattare", "accettare",
            "addestrare", "affermare", "affrontare", "agire", "alimentare", "alzarsi", "annunciare", "appartenere", "arrivare", "bagnare", "battere", "bruciare",
            "cambiare", "catturare", "celebrare", "cercare", "colpire", "condividere", "conoscere", "crescere", "cucire", "curare", "decidere", "desiderare",
            "dimenticare", "dirigere", "dipingere", "diventare", "dormire", "durare", "effettuare", "esplorare", "evaporare", "fagocitare", "falsificare",
            "fare", "fingere", "finire", "giocare", "lavorare", "mangiare", "mentire", "morire", "navigare", "osservare", "parlare", "pensare", "perdere",
            "piacere", "portare", "preparare", "principiare", "prendere", "riscaldare", "rivelare", "salire", "scoprire", "scrivere", "segnare", "sognare",
            "stare", "studiare", "sostituire", "trattare", "trovare", "vedere", "vincere", "volere", "avvicinarsi", "battere", "chiedere", "cominciare",
            "correre", "diventare", "finire", "incontrare", "interrompere", "parlare", "pensare", "preparare", "vedere", "venire", "scrivere", "soprendere",
            "sostenere", "trattare", "uscire", "valutare", "votare", "andare", "sperimentare", "decidere", "esaminare", "analizzare", "rispondere",
            "fare", "sognare", "andare", "arrostire", "continuare", "esprimere", "percepire", "bastare", "provare", "porgere", "parlare", "affermare",
            "scrivere", "tradurre", "ridere", "portare", "viaggiare", "attingere", "impazzire", "vincere", "arrivare", "cercare"           ,"abbandonarsi", "accantonare", "accasarsi", "accompagnarsi", "adoperare", "agitare", "alleggerire", "alimentarsi", "ammassare", "appacificare",
            "appoggiare", "assopirsi", "attribuire", "avvilire", "burlarsi", "calare", "cancellarsi", "cavarsela", "chiarirsi", "cogliersi",
            "compiacersi", "confondersi", "consentire", "continuarsi", "coricare", "crescere", "decollare", "definire", "discutere", "dissolversi",
            "divagare", "eclissarsi", "elargire", "evidenziarsi", "fuggire", "giustificarsi", "lamentarsi", "lanciarsi", "mentire", "mobilitarsi",
            "monetizzare", "navigarsi", "nascere", "ostinarsi", "parcheggiare", "pattugliare", "perdersi", "persuadere", "piegarsi", "precipitarsi",
            "prepararsi", "procurarsi", "promuovere", "provvedere", "raccontarsi", "raccogliere", "rappresentarsi", "reagire", "recarsi", "remare",
            "rincorrere", "riprendersi", "rivelarsi", "salire", "sbattere", "selezionarsi", "sperarsi", "sputare", "stabilizzarsi", "staccarsi",
            "suggerire", "superarsi", "svelarsi", "svegliare", "tattarsi", "terminarsi", "trasformarsi", "unirsi", "valutarsi", "vagare",
            "verificarsi", "vedersela", "vendersi", "venirsi", "verificare", "vogarsi", "volgersi", "avvicinarsi", "balzare", "bisognare",
            "bruciare", "cercarsi", "colpire", "confidare", "consultare", "crearsi", "disinnescare", "divertirsi", "emergere", "eseguire",
            "farsi", "flettere", "fondersi", "gridare", "imitare", "incontrarsi", "inseguito", "inventarsi", "lanciarsi", "lavorarsi",
            "manifestarsi", "nuotarsi", "opporsi", "parlarsi", "percepirsi", "riemergere", "riscontrare", "sbarcare", "sentirsi", "soffermarsi",
            "sopportarsi", "spostarsi", "stimarsi", "suscitare", "togliersi", "tornare", "tuffarsi", "uscire", "usarsi", "vedersi",
            "vivere", "volere", "abdicare", "accomunare", "ampliare", "appoggiarsi", "avventurarsi", "accorgersi", "apprezzare", "assaporarsi",
            "avanzare", "compromettersi", "crescere", "dissolversi", "esprimersi", "farcela", "fluttuare", "fondersi", "gravitare",
            "impegnarsi", "infischiarsi", "investire", "languire", "muoversi", "navigare", "offrirsi", "percepire", "prestarsi", "raccogliersi",
            "recarsi", "rifugiarsi", "restaurarsi", "rivelarsi", "riposarsi", "scivolarsi", "sciogliersi", "scomparire", "sforzarsi",
            "stabilizzarsi", "stravolgersi", "tendenziare", "tuffarsi", "ventilarsi", "vivacizzarsi", "imprigionarsi", "frullarsi",
            "barricarsi", "confondersi", "risolversi", "tremare", "valutarsi", "rapirsi", "salvarsi", "segregarsi", "ritrovarsi",
            "trascorrere", "infatuarsi", "meditare", "salirsi", "smarirsi", "sottoporsi", "lanciarsi", "rinchiudersi", "rivedersi",
            "accanirsi", "avere", "sopravvivere", "consolarsi", "battibeccare", "avvicinarsi", "cacciarsi", "mordicchiare", "frenarsi",
            "barcollarsi", "puzzare", "aggirarsi", "rancorarsi", "preoccuparsi", "spogliarsi", "frenarsi", "tradirsi", "resistere",
            "mettersi", "riuscirsi", "ristorarsi", "scorgersi", "svanire", "dissociarsi", "affrontarsi", "ammorbidirsi", "decidersi",
            "salirsi", "grattarsi", "spaventarsi", "riconoscersi", "stancarsi", "farcela", "soffrire", "rinforzarsi", "asciugarsi",
            "prepararsi", "recuperarsi", "tergiversare", "verificarsi", "scoprire", "rimanere", "indossare", "riprendersi", "ragionarsi",             "adombrare",
    "assurgere",
    "cogitare",
    "desumere",
    "dirimere",
    "infervorare",
    "perseverare",
    "procrastinare",
    "tralignare",
    "vaneggiare",
    "stigmatizzare",
    "conculcare",
    "soggiacere",
    "obliterare",
    "deferire",
    "incardinare",
    "riscuotere",
    "distillare",
    "implorare",
    "confutare",
    "disquisire",
    "appecoronarsi",
    "ravvisare",
    "sciorinare",
    "disilludere",
    "apporre",
    "intercalare",
    "delibare",
    "riverberare",
    "profferire",
    "soppesare",
    "evincere",
    "annegare",
    "sorvolare",
    "trascendere",
    "ripudiare",
    "redarguire",
    "collimare",
    "scongiurare",
    "osteggiare",
    "sbrogliare",
    "deambulare",
    "trarre",
    "delucidare",
    "preterire",
    "subentrare",
    "esimersi",
    "abdicare",
    "concupire",
    "caldeggiare",
    "imbastire",
    "sovvenire",
    "dileguarsi",
    "trasparire",
    "egemonizzare",
    "trasudare",
    "glissare",
    "subissare",
    "estromettere",
    "inveire",
    "lapidare",
    "annichilire",
    "rammentare",
    "scardinare",
    "propugnare",
    "avvincere",
    "scernere",
    "deturpare",
    "decantare",
    "abbarbicare",
    "riscuotere",
    "instaurare",
    "perorare",
    "esautorare",
    "implicare",
    "ottundere",
    "asserire",
    "abbindolare",
    "districare"
        };
        private static readonly List<string> Eventi = new List<string> {              "Fingi di avere un litigio violento con il tuo peluche",
            "Fai finta di inseguire un topo immaginario in camera",
            "Simula di essere caduto dal letto e di non riuscire a rialzarti",
            "Fai finta di arrabbiarti con il muro perché ti ha parlato male",
            "Fingi di mangiare una banana rumorosamente mentre parli",
            "Simula di avere una crisi di panico perché hai perso una moneta",
            "Fai finta che una mosca gigantesca stia attaccando la stanza",
            "Urla che un alieno ti sta rapendo e inizia a negoziare la tua libertà",
            "Fai finta di tirare pugni al cuscino per allenarti alla boxe",
            "Simula di essere inseguito da un'cerbiatto in camera tua",
            "Fingi di ricevere una pizza che non hai ordinato e litiga con il corriere immaginario",
            "Fai finta di aver trovato un serpente sotto il letto e chiedi aiuto alla persona in chiamata",
            "Inizia a parlare con una pianta come se fosse la tua migliore amica",
            "Simula di dover insegnare a un gruppo di gatti come saltare correttamente",
            "Fai finta che ci sia un fantasma che continua a spegnere le luci",
            "Urla che hai rotto il pavimento saltando troppo forte",
            "Fai finta di non trovare il tuo telefono, mentre stai chiaramente parlando al telefono",
            "Simula di combattere contro un vampiro che vuole entrare dalla finestra",
            "Fai finta di dover scalare un armadio per recuperare un oggetto importante",
            "Fai finta di essere attaccato da un robot aspirapolvere impazzito",
            "Fingi che il tuo animale immaginario si sia ribellato contro di te",
            "Fai finta di perdere una scarpa sotto il letto e lamentati come se fosse la fine del mondo",
            "Simula di trovarti improvvisamente in una tempesta di sabbia in camera tua",
            "Fingi che un cameriere invisibile ti stia servendo un pasto lussuoso",
            "Fai finta che il tuo letto sia diventato un'isola e non puoi scendere",
            "Fai finta che un ragno enorme ti stia inseguendo sul soffitto",
            "Simula di dover difendere il frigorifero da un orso polare immaginario",
            "Urla che il pavimento è lava e non puoi camminare",
            "Fingi di ballare il tango con una sedia e fallo sembrare super serio",
            "Simula di costruire un castello con i cuscini e di difenderlo da invasori immaginari",
            "Fingi di dover convincere un gruppo di fantasmi a lasciare la tua stanza",
            "Fai finta di avere un dialogo acceso con il tuo riflesso nello specchio",
            "Fingi di perdere il controllo della tua sedia girevole e di cadere rovinosamente",
            "Fai finta di cucinare una torta ma urla che ti manca l'ingrediente principale",
            "Fingi di discutere con il tuo computer perché non vuole ascoltarti",
            "Fai finta di dover convincere un gruppo di piccioni immaginari a uscire dalla stanza",
            "Urla che la tua lampada si è improvvisamente trasformata in un serpente",
            "Simula di trovare un antico tesoro nascosto nel tuo armadio",
            "Fai finta che un tuo vicino immaginario stia bussando disperatamente alla porta",
            "Fingi di essere attaccato da un drone impazzito che vuole rubarti i capelli",
            "Fai finta di cercare un oggetto invisibile che continua a spostarsi da solo",
            "Simula di avere una crisi esistenziale perché hai dimenticato il compleanno della tua pianta",
            "Fingi che la tua stanza si sia improvvisamente allagata e devi nuotare",
            "Fai finta che il tuo cuscino ti abbia insultato e inizia a discutere con lui",
            "Simula di lanciare una sfida a braccio di ferro a una mano immaginaria",
            "Fingi di organizzare una riunione importante con i tuoi vestiti appesi",
            "Fai finta di ricevere una chiamata dall'aldilà e rispondi al telefono immaginario",
            "Fingi di essere posseduto da un personaggio famoso e parli con il suo accento",
            "Simula di avere una crisi isterica perché hai perso il tuo calzino preferito",
            "Fai finta che un tappeto volante ti stia portando via",
            "Simula di cercare di fermare un'invasione aliena dalla finestra",
            "Fingi di ricevere una consegna di 1000 palloncini e di non sapere cosa fare",
            "Fai finta di dover riparare urgentemente un'astronave invisibile",
            "Simula di essere coinvolto in un duello con una spada immaginaria",
            "Fai finta di perdere un oggetto importante e urlare per la stanza.",
            "Simula di ricevere una telefonata furiosa da un ex partner.",
            "Fai finta di ballare in modo goffo mentre canti una canzone stonata.",
            "Chiedi a voce alta al muro: 'Ma dov'è il mio unicorno rosa?'",
            "Fai finta di discutere con un immaginario cameriere che ti ha servito male.",
            "Parla con accento strano e fingi di essere un turista perso.",
            "Fai un discorso motivazionale esagerato a te stesso davanti al nulla.",
            "Fai finta di litigare con un oggetto inanimato, tipo una sedia o il cuscino.",
            "Imita il verso di un animale per 30 secondi senza spiegare.",
            "Recita una poesia d'amore a un oggetto casuale nella stanza.",
            "Fai finta di chiedere scusa al tuo computer per averlo trattato male.",
            "Fai finta di soffocare per 5 secondi e poi torna normale come se nulla fosse.",
            "Dichiara il tuo amore eterno alla lampada nella stanza.",
            "Urla: 'Chi ha preso il mio panino?' e guardati intorno sospettoso.",
            "Fai finta di essere un presentatore di un talent show e introduci un oggetto casuale.",
            "Fai finta di dover convincere un ladro immaginario a non rubarti qualcosa.",
            "Imita il tuo insegnante preferito mentre spieghi qualcosa di assurdo.",
            "Urla: 'C'è un fantasma qui!' e fingi di nasconderti.",
            "Parla con un oggetto immaginario e litiga con lui come se fosse vivo.",
            "Fai finta di essere uno chef famoso che recensisce un cibo immaginario.",
            "Fingi di essere un influencer che fa un tutorial ridicolo di bellezza.",
            "Inizia a fare piegamenti per terra senza spiegare perché.",
            "Fingi di parlare con il Presidente di una nazione per un problema assurdo.",
            "Accusa la lampada di aver rubato il tuo portafoglio.",
            "Fai finta di dover confessare un segreto incredibile al muro.",
            "Simula un litigio con un fantasma e urla: 'Lasciami in pace!'",
            "Fingi di essere in un musical e canta tutto ciò che fai.",
            "Urla: 'Non ci posso credere!' e poi torna calmo come nulla fosse.",
            "Chiedi a voce alta: 'Perché mi succede sempre questo?!' guardando il pavimento.",    
    "Fai finta di essere un gallo e canta al mattino",
    "Simula di essere posseduto da uno spirito maligno",
    "Chiama una persona random e confessa di aver rubato qualcosa",
    "Racconta ad alta voce i dettagli del tuo ultimo incubo",
    "Fai finta di piangere disperatamente per un motivo assurdo",
    "Imita i versi di un delfino ogni 10 secondi",
    "Chiedi scusa a una sedia per averla usata troppo",
    
    "Fai il verso di un gatto arrabbiato mentre parli normalmente",
    "Dichiara di essere allergico all'acqua mentre bevi",
    "Fingi di essere un robot con un grave malfunzionamento",
    "Ripeti l'ultima frase che dici tre volte per 5 minuti",
    "Prova a mettere in discussione l'esistenza della gravità",
   
    
    "Parla con il tuo riflesso come se fosse reale",
    "Imita l'urlo di Tarzan improvvisamente",
    "Simula una litigata con un fantasma nella stanza",
    "Confessa ad alta voce di aver rubato soldi a qualcuno",
    "Parla con un tono sussurrato per tutta la chiamata",
    "Accusa il frigorifero di complottare contro di te",
    "Prova a recitare una scena romantica a caso",
    "Dichiara il tuo amore eterno a un oggetto casuale nella stanza",
    "Fingi di ricevere una proposta di matrimonio immaginaria",
    "Chiama la persona in chiamata con il nome del tuo ex",
    "Dichiara che hai scoperto una teoria della cospirazione",
    "Fai finta di strangolarti e di morire drammaticamente",
    "Prova a fare rumori strani con la bocca ogni due parole",
    "Prova a ballare un tango con un cuscino",
    "Parla del tuo peggior imbarazzo come se fosse stato ieri",
    "Fai finta di ricordarti un segreto scioccante e poi non dirlo",
    "Prova a far capire di essere sotto interrogatorio della polizia",
    "Canta un jingle pubblicitario anni '80 a caso",
    "Fai il mimo di un ninja mentre parli al telefono",
    "Urla una parola volgare casuale senza scusarti",
    "Parla con la tua mano come se fosse il tuo terapeuta",
    "Simula di essere una rockstar che si esibisce in bagno",
    "Sussurra 'ho paura che mi stiano ascoltando' in continuazione",
    "Racconta ad alta voce una scena assurda di un film immaginario",
    "Fingi di ricevere un ordine militare in diretta",
    "Imita l'accento di un'altra nazionalità in modo ridicolo",
    "Simula una reazione allergica estrema improvvisamente",
    "Confessa di avere una relazione con un oggetto inanimato",
    "Fai finta di vomitare mentre parli al telefono",
    "Canta una canzone volgare inventata sul momento",
    "Fai rumori disgustosi mentre mastichi aria",
    "Fingi di essere una star del porno in incognito",
    "Fai versi di animale senza preavviso ogni minuto",
    "Urla 'chi ha nascosto il mio unicorno?' con rabbia",
    "Fai un discorso motivazionale assurdo ad alta voce",
    "Prova a convincere la persona che sei un alieno sotto copertura",
    "Canta una serenata romantica al tuo letto",
    "Simula una rissa con una persona invisibile",
    "Confessa di aver venduto la tua anima per dei biscotti",
    "Prova a fare un provino per un film horror davanti alla videocamera",
    "Fai versi di un dinosauro in estinzione improvvisamente",
    "Urla in modo totalmente incoerente per 15 secondi",
    "Fingi di essere arrestato in diretta senza motivo",
    "Racconta una storia di vita completamente falsa e ridicola",
    "Dichiara che hai scoperto di essere immortale",
    "Simula di litigare con una pianta da interno",
    "Urla il nome di una persona a caso e chiedi dove sia",
    "Fingi di ricevere un massaggio molto sensuale",
    "Imita una telefonata falsa con un amante segreto",
    "Simula di essere un sopravvissuto all'apocalisse",
    "Prova a convincere la persona che sei un vampiro",
    "Racconta una storia erotica inventata con dettagli assurdi",
    "Urla 'chi ha mangiato la mia pizza?!' con rabbia folle",
    "Fai rumori di una tempesta ogni volta che parli",
    "Prova a fare un annuncio pubblico come fossi alla radio",
    "Imita un clown inquietante che ride senza motivo",
    "Prova a parlare solo in versi poetici per 10 minuti",
    "Dichiara che sei il leader di una setta segreta",
    "Fai finta di ricordarti improvvisamente una vita passata",
    "Prova a far sembrare che hai un problema di dissociazione",
    "Fai una dichiarazione pubblica contro i frigoriferi",
    "Racconta un tuo sogno erotico in modo eccessivamente dettagliato",
    "Crea un dialogo con una voce immaginaria nella tua testa",
    "Urla una battuta volgare come se fosse normale",
    "Fingi di essere un televenditore vendendo cose inutili",
    "Prova a convincere l'altra persona che stai vedendo fantasmi"};
        private static readonly List<string> Imprevisti = new List<string> {              "Racconta di quando hai parlato con un albero.",
    "Convinci che i polli hanno inventato internet.",
    "Racconta di quella volta che hai mangiato un arcobaleno.",
    "Convinci che i pesci respirano aria solo di notte.",
    "Racconta di quando hai trovato oro in una lattina di soda.",
    "Convinci che le nuvole sono fatte di zucchero filato.",
    "Racconta di quando hai cavalcato uno struzzo.",
    "Convinci che i gatti sanno guidare le auto.",
    "Racconta di quella volta che hai visto un orso fare yoga.",
    "Convinci che la pizza è un'invenzione aliena.",
    "Racconta di quando hai insegnato a un cane a cantare.",
    "Convinci che la Luna è una lampadina gigante.",
    "Racconta di quando hai trovato un biglietto per Marte.",
    "Convinci che le carote brillano al buio.",
    "Racconta di quella volta che hai pescato con una forchetta.",
    "Convinci che il tuo telefono ti parla nei sogni.",
    "Racconta di quando hai fatto amicizia con un robot.",
    "Convinci che le banane sono telecomandi universali.",
    "Racconta di quella volta che hai visto un gatto camminare sulle pareti.",
    "Convinci che l'acqua può diventare invisibile.",
    "Racconta di quando hai fatto volare un tappeto.",
    "Convinci che puoi parlare con le piante.",
    "Racconta di quella volta che hai usato il vento per cucinare.",
    "Convinci che gli aerei sono enormi aquiloni.",
    "Racconta di quando hai dormito su una nuvola.",
    "Convinci che il ghiaccio è un tipo di gelato segreto.",
    "Racconta di quella volta che hai fatto amicizia con un alieno.",
    "Convinci che puoi teletrasportarti schioccando le dita.",
    "Racconta di quando hai trovato un drago nel garage.",
    "Convinci che la pioggia cade solo perché i giganti piangono.",
    "Racconta di quella volta che hai camminato sopra l'acqua.",
    "Convinci che il sole è un'enorme arancia.",
    "Racconta di quando hai visto un ragno ballare.",
    "Convinci che i dinosauri vivono ancora, ma si nascondono bene.",
    "Racconta di quella volta che hai vinto una gara contro un ghepardo.",
    "Convinci che le montagne si muovono lentamente.",
    "Racconta di quando hai costruito un castello con i popcorn.",
    "Convinci che la sabbia è in realtà polvere di stelle.",
    "Racconta di quella volta che hai fatto un picnic sulla Luna.",
    "Convinci che gli specchi sono portali segreti.",
    "Racconta di quando hai parlato con una statua.",
    "Convinci che gli orologi girano al contrario in un'altra dimensione.",
    "Racconta di quella volta che hai usato una barca come skateboard.",
    "Convinci che puoi leggere i pensieri del tuo gatto.",
    "Racconta di quando hai costruito una casa sull'acqua.",
    "Convinci che il vento ha un nome segreto.",
    "Racconta di quella volta che hai visto una zebra in città.",
    "Convinci che gli alberi possono camminare.",
    "Racconta di quando hai catturato una stella cadente.",
    "Convinci che le farfalle sono messaggere degli alieni.",
    "Racconta di quella volta che hai perso un pallone nello spazio.",
    "Convinci che i fulmini sono la rabbia di un drago.",
    "Racconta di quando hai trovato una bicicletta invisibile.",
    "Convinci che la neve è il risultato di una guerra di cuscini nel cielo.",
    "Racconta di quella volta che hai trovato una chiave gigante.",
    "Convinci che puoi controllare il tempo schioccando le dita.",
    "Racconta di quando hai fatto un bagno in una fontana magica.",
    "Convinci che i computer funzionano grazie ai criceti.",
    "Racconta di quella volta che hai parlato con il tuo riflesso.",
    "Convinci che i treni sono serpenti metallici.",
    "Racconta di quando hai trovato un messaggio in una bottiglia.",
    "Convinci che i fantasmi vivono nel tuo frigorifero.",
    "Racconta di quella volta che hai trovato un portale in un libro.",
    "Convinci che gli elefanti possono diventare invisibili.",
    "Racconta di quando hai trovato una bacchetta magica sotto il letto.",
    "Convinci che la musica nasce dagli alberi.",
    "Racconta di quella volta che hai costruito un razzo con le matite.",
    "Convinci che puoi vedere il futuro nei riflessi dell'acqua.",
    "Racconta di quando hai incontrato una sirena in piscina.",    "Convinci che le stelle sono fori nel cielo.",
    "Racconta di quando hai visto un cane usare gli occhiali.",
    "Convinci che le penne possono scrivere da sole.",
    "Racconta di quella volta che hai insegnato a un gatto a cucinare.",
    "Convinci che le montagne sono solo giganti addormentati.",
    "Racconta di quando hai trovato una macchina del tempo in soffitta.",
    "Convinci che l’oceano è solo una piscina molto grande.",
    "Racconta di quella volta che hai visto un elefante giocare a calcio.",
    "Convinci che le zanzare sono droni spia in miniatura.",
    "Racconta di quando hai ballato con un pinguino.",
    "Convinci che i fiori crescono più velocemente se gli canti.",
    "Racconta di quella volta che hai costruito una barca di cioccolato.",
    "Convinci che il ghiaccio può trasformarsi in diamanti.",
    "Racconta di quando hai parlato con un temporale.",
    "Convinci che i ragni sono in realtà creature magiche.",
    "Racconta di quella volta che hai fatto una gara di salto con una rana.",
    "Convinci che i vulcani sono solo teiere giganti.",
    "Racconta di quando hai visto un’aquila portare la spesa.",
    "Convinci che la sabbia è il risultato di mille castelli distrutti.",
    "Racconta di quella volta che hai nuotato in un mare di gelatina.",
    "Convinci che gli alberi sono antenne per parlare con lo spazio.",
    "Racconta di quando hai insegnato a un pappagallo a fare il DJ.",
    "Convinci che puoi comunicare con i lampioni.",
    "Racconta di quella volta che hai trovato una chiave per un regno magico.",
    "Convinci che i fiumi sono nastri trasportatori naturali.",
    "Racconta di quando hai trovato un piccolo drago nel forno.",
    "Convinci che gli specchi riflettono anche il passato.",
    "Racconta di quella volta che hai fatto amicizia con un'ombra.",
    "Convinci che puoi fermare il tempo starnutendo.",
    "Racconta di quando hai visto una balena volare.",
    "Convinci che i pianeti ballano quando nessuno li guarda.",
    "Racconta di quella volta che hai trovato una carota gigante in giardino.",
    "Convinci che il vento porta messaggi segreti.",
    "Racconta di quando hai preso una stella per decorare l'albero di Natale.",
    "Convinci che puoi parlare con il fuoco.",
    "Racconta di quella volta che hai costruito un'astronave di carta.",
    "Convinci che le farfalle sono ex stelle cadenti.",
    "Racconta di quando hai trovato un dinosauro nascosto in una grotta.",
    "Convinci che le rocce hanno dei segreti millenari.",
    "Racconta di quella volta che hai visto un cammello in un supermercato.",
    "Convinci che i cappelli ti fanno leggere la mente.",
    "Racconta di quando hai usato una nuvola come materasso.",
    "Convinci che i colori hanno un sapore.",
    "Racconta di quella volta che hai vinto una lotta contro il vento.",
    "Convinci che i cani hanno inventato il frisbee.",
    "Racconta di quando hai visto un gatto guidare una bicicletta.",
    "Convinci che i vulcani emettono musica classica.",
    "Racconta di quella volta che hai trovato un libro che parlava.",
    "Convinci che i mattoni sono creature che dormono.",
    "Racconta di quando hai trovato un tappeto volante al mercato.",
    "Convinci che le stelle hanno odore di vaniglia.",
    "Racconta di quella volta che hai costruito un igloo di zucchero.",
    "Convinci che gli aerei funzionano grazie a bolle di sapone.",
    "Racconta di quando hai insegnato a un delfino a cantare.",
    "Convinci che le nuvole parlano quando piove.",
    "Racconta di quella volta che hai visto un serpente con un cappello.",
    "Convinci che puoi sciare sulla sabbia.",
    "Racconta di quando hai usato un'anguria come casco.",
    "Convinci che i treni si muovono grazie a caffè.",
    "Racconta di quella volta che hai dormito in un albero gigante.",
    "Convinci che il cielo cambia colore perché si diverte.",
    "Racconta di quando hai trovato una porta verso un mondo di caramelle.",
    "Convinci che il mare canta quando è felice.",
    "Racconta di quella volta che hai visto un robot andare in vacanza.",
    "Convinci che i prati sono tappeti verdi giganti.",
    "Racconta di quando hai trovato una moneta gigante sotto il letto.",
    "Convinci che la Terra è in realtà un enorme pallone gonfiabile.",
    "Racconta di quella volta che hai visto una tartaruga volare.",
    "Convinci che le stelle fanno a gara a chi brilla di più.",    "Convinci l'ascoltatore che puoi rompere un muro a testate.",
    "Racconta di quella volta che hai rubato un'ambulanza per andare al supermercato.",
    "Convinci l'ascoltatore che i piccioni stanno pianificando una rivolta.",
    "Racconta di come hai sopravvissuto a un attacco di un robot assassino.",
    "Convinci l'ascoltatore che sei un ricercato in tre stati.",
    "Racconta di quella volta che hai lanciato un microonde dalla finestra.",
    "Convinci l'ascoltatore che stai parlando da una cella frigorifera.",
    "Racconta di quella volta che hai duellato con un cacciavite.",
    "Convinci l'ascoltatore che il tuo vicino è un vampiro.",
    "Racconta di come hai fermato una rapina usando solo una banana.",
    "Convinci l'ascoltatore che hai accidentalmente distrutto una statua storica.",
    "Racconta di quella volta che hai affrontato un leone armato di un ombrello.",
    "Convinci l'ascoltatore che hai fatto esplodere una piscina con un petardo.",
    "Racconta di come hai venduto un'auto rubata senza accorgertene.",
    "Convinci l'ascoltatore che hai trovato un bazooka in soffitta.",    "Convinci l'ascoltatore che hai buttato qualcuno giù da una scogliera per errore.",
    "Racconta di quella volta che hai preso a pugni un albero finché non è caduto.",
    "Convinci l'ascoltatore che sei scappato da un combattimento clandestino.",
    "Racconta di come hai cercato di domare un cinghiale con una mazza da baseball.",
    "Convinci l'ascoltatore che hai sabotato i freni di un'auto... per sbaglio.",
    "Racconta di quella volta che hai lanciato una televisione da un tetto durante una lite.",
    "Convinci l'ascoltatore che sei stato coinvolto in un inseguimento a mano armata.",
    "Racconta di quella volta che hai rubato un carro armato per andare a lavoro.",
    "Convinci l'ascoltatore che hai scambiato un coltello con un souvenir di plastica durante un furto.",
    "Racconta di come hai inseguito un ladro con una motosega spenta.",
    "Convinci l'ascoltatore che hai usato un estintore per difenderti in una rissa.",
    "Racconta di quella volta che hai fatto esplodere una porta usando la dinamite.",
    "Convinci l'ascoltatore che sei stato costretto a fuggire da un edificio in fiamme che hai appiccato tu.",    "Convinci l'ascoltatore che hai staccato un tavolo da un bar con la forza per portarlo a casa.",
    "Racconta di quella volta che hai scatenato una rissa a una festa per difendere la tua pizza.",
    "Convinci l'ascoltatore che sei stato cacciato da un museo per aver toccato una statua .",
    "Racconta di come hai sfondato una porta a calci perché qualcuno ti aveva rubato il posto auto.",
    "Convinci l'ascoltatore che sei stato inseguito da un gruppo di gente armata di zappe.",
    "Racconta di quella volta che sei stato sorpreso nudo in una situazione molto imbarazzante.",
    "Convinci l'ascoltatore che hai litigato con un vigile urbano e sei finito a lanciare pietre.",
    "Racconta di come hai lanciato un secchio d'acqua addosso a due persone che si baciavano.",
    "Convinci l'ascoltatore che sei stato arrestato per aver fatto irruzione in un negozio completamente nudo.",
    "Racconta di quella volta che hai strappato i vestiti di un amico per dimostrare che aveva un tatuaggio.",
    "Convinci l'ascoltatore che hai dato un pugno a un vicino che ti spiava dalla finestra.",
    "Racconta di come sei finito a correre seminudo per strada dopo una scommessa persa.",
    "Convinci l'ascoltatore che hai schiaffeggiato qualcuno per aver detto qualcosa di offensivo.",
    "Racconta di quella volta che hai cercato di scappare da un appuntamento inventando un finto incendio.",
    "Convinci l'ascoltatore che hai rubato la macchina del tuo ex per vendicarti.",
    "Racconta di come sei stato cacciato da una sauna per aver provocato una rissa con un gruppo di sconosciuti.",
    "Convinci l'ascoltatore che hai distrutto un materasso a calci durante una discussione.",
    "Racconta di quella volta che hai spinto qualcuno in piscina per chiudere una lite.",
    "Convinci l'ascoltatore che sei stato coinvolto in una fuga rocambolesca da un club privato.",
    "Racconta di come hai minacciato un tassista di lasciarti guidare al posto suo."};
        public static string GeneraParola()
        {
            Random r = new Random();
            int f = r.Next(0, 21);
            if (f < 18)
            {
                return Parole[r.Next(0, Parole.Count)];
            }
            else if (f<19)
            {
                return Imprevisti[r.Next(0, Imprevisti.Count)];
            }
            else
            {
                return Eventi[r.Next(0, Eventi.Count)];
            }
        }
    }
}
